In [1]:
#importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#import dataset
data = pd.read_csv('DATASETNEW 1200 lines.csv')

In [3]:
data

Day        Date  CodedDay  Zone  Weather  Temperature  1
0     Wednesday  06-01-2022         3     2       35           17  2
1     Wednesday  06-01-2022         3     3       36           16  3
2     Wednesday  06-01-2022         3     4       27           25  5
3     Wednesday  06-01-2022         3     5       23           23  3
4     Wednesday  06-01-2022         3     6       18           42  2
...         ...         ...       ...   ...      ...          ... ..
1194     Sunday  18-01-2022         7    25       25           21  4
1195     Sunday  18-01-2022         7    24       26           22  4
1196     Sunday  18-01-2022         7    23       24           23  4
1197     Sunday  18-01-2022         7    22       23           24  4
1198     Sunday  18-01-2022         7    21       22           25  4

[1199 rows x 7 columns]

In [4]:
data.head(30)

Day        Date  CodedDay  Zone  Weather  Temperature  1
0   Wednesday  06-01-2022         3     2       35           17  2
1   Wednesday  06-01-2022         3     3       36           16  3
2   Wednesday  06-01-2022         3     4       27           25  5
3   Wednesday  06-01-2022         3     5       23           23  3
4   Wednesday  06-01-2022         3     6       18           42  2
5   Wednesday  06-01-2022         3     7       11           14  2
6   Wednesday  06-01-2022         3     8       45           28  4
7   Wednesday  06-01-2022         3     9       39           18  5
8   Wednesday  06-01-2022         3    10       25            9  4
9   Wednesday  06-01-2022         3    11       39            7  5
10  Wednesday  06-01-2022         3    12       22           29  2
11  Wednesday  06-01-2022         3    13       16           29  2
12  Wednesday  06-01-2022         3    14       20           25  1
13  Wednesday  06-01-2022         3    15       39           31  3
14  Wednesday  06-01-2022         3    16       40           44  1
15  Wednesday  06-01-2022         3    17        4           34  4
16  Wednesday  06-01-2022         3    18       40           45  4
17  Wednesday  06-01-2022         3    19        5           32  4
18  Wednesday  06-01-2022         3    20       24           40  1
19  wednesday  06-01-2022         3    12       21           22  2
20  wednesday  06-01-2022         3    13       31           23  1
21  wednesday  06-01-2022         3    11       21           22  2
22  wednesday  06-01-2022         3    12       22           12  3
23  wednesday  06-01-2022         3    11       23           22  2
24  wednesday  06-01-2022         3    22       23           22  2
25  wednesday  06-01-2022         3    11       23           22  1
26  wednesday  06-01-2022         3    33       12           11  3
27  wednesday  06-01-2022         3    22       33           12  4
28  wednesday  06-01-2022         3    11       22           33  4
29  wednesday  06-01-2022         3    22       33           22  1

In [5]:
data.tail()

Day        Date  CodedDay  Zone  Weather  Temperature  1
1194  Sunday  18-01-2022         7    25       25           21  4
1195  Sunday  18-01-2022         7    24       26           22  4
1196  Sunday  18-01-2022         7    23       24           23  4
1197  Sunday  18-01-2022         7    22       23           24  4
1198  Sunday  18-01-2022         7    21       22           25  4

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1199 entries, 0 to 1198
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Day          1199 non-null   object
 1   Date         1199 non-null   object
 2   CodedDay     1199 non-null   int64 
 3   Zone         1199 non-null   int64 
 4   Weather      1199 non-null   int64 
 5   Temperature  1199 non-null   int64 
 6   1            1199 non-null   int64 
dtypes: int64(5), object(2)
memory usage: 65.7+ KB


In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le = LabelEncoder()

In [9]:
data['Date'] = le.fit_transform(data['Date'])
data

Day  Date  CodedDay  Zone  Weather  Temperature  1
0     Wednesday     1         3     2       35           17  2
1     Wednesday     1         3     3       36           16  3
2     Wednesday     1         3     4       27           25  5
3     Wednesday     1         3     5       23           23  3
4     Wednesday     1         3     6       18           42  2
...         ...   ...       ...   ...      ...          ... ..
1194     Sunday    12         7    25       25           21  4
1195     Sunday    12         7    24       26           22  4
1196     Sunday    12         7    23       24           23  4
1197     Sunday    12         7    22       23           24  4
1198     Sunday    12         7    21       22           25  4

[1199 rows x 7 columns]

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1199 entries, 0 to 1198
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Day          1199 non-null   object
 1   Date         1199 non-null   int32 
 2   CodedDay     1199 non-null   int64 
 3   Zone         1199 non-null   int64 
 4   Weather      1199 non-null   int64 
 5   Temperature  1199 non-null   int64 
 6   1            1199 non-null   int64 
dtypes: int32(1), int64(5), object(1)
memory usage: 61.0+ KB


In [11]:
x= data.iloc[:,2:6].values
y= data.iloc[:,6:7].values

In [12]:
x

array([[ 3,  2, 35, 17],
       [ 3,  3, 36, 16],
       [ 3,  4, 27, 25],
       ...,
       [ 7, 23, 24, 23],
       [ 7, 22, 23, 24],
       [ 7, 21, 22, 25]], dtype=int64)

In [13]:
x.shape

(1199, 4)

In [14]:
y=y.flatten()

In [15]:
y.shape

(1199,)

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20,random_state=0
                                                   )

In [18]:
x_train.shape,y_train.shape

((959, 4), (959,))

In [19]:
x_test.shape,y_test.shape

((240, 4), (240,))

In [20]:
#feature Scaling

from sklearn.preprocessing import StandardScaler

In [21]:
sc= StandardScaler()

In [22]:
x_train= sc.fit_transform(x_train)
x_test= sc.fit_transform(x_test)

In [23]:
x_train

array([[ 0.25719785, -1.06801338,  0.41419277, -1.02590952],
       [-0.89269836, -1.42124308, -1.03828836, -0.81125974],
       [ 1.40709406,  0.48619729,  1.09771331,  1.01326331],
       ...,
       [-0.31775026,  0.06232165, -1.03828836, -0.81125974],
       [-1.46764647, -0.22026211, -1.12372843, -0.91858463],
       [-0.89269836, -1.42124308, -0.01300756, -0.81125974]])

In [24]:
#random forest
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=300, random_state = 0)

In [25]:
 regressor.fit(x_train,y_train)

RandomForestRegressor(n_estimators=300, random_state=0)

In [26]:
y_pred=regressor.predict(x_test)

In [27]:
y_pred

array([2.44666667, 3.76239438, 2.67      , 2.88      , 2.51611111,
       3.21333333, 2.6       , 2.4618924 , 3.07      , 2.61333333,
       3.76239438, 2.75486324, 3.76239438, 3.76239438, 3.74975938,
       2.82066667, 2.98368783, 3.1228459 , 1.60888889, 2.69333333,
       2.85911697, 2.74909349, 1.55333333, 1.62      , 2.69396888,
       2.8493433 , 3.68638377, 3.1228459 , 2.83      , 1.895     ,
       3.46333333, 2.65666667, 3.52337703, 2.34944444, 3.72701797,
       3.41      , 3.1228459 , 2.85911697, 2.44      , 2.83666667,
       2.08611111, 2.22666667, 2.73333333, 3.92666667, 2.18333333,
       2.37333333, 3.76239438, 2.24638889, 2.75486324, 1.98666667,
       2.77083333, 3.64666667, 3.05      , 3.67      , 2.55666667,
       3.84666667, 1.76472222, 3.12444444, 2.03444444, 2.85911697,
       3.51666667, 3.08      , 3.05103738, 3.79666667, 2.45      ,
       3.71333333, 3.55013149, 2.81666667, 3.74666667, 3.61333333,
       2.79666667, 3.11333333, 7.15333333, 3.55666667, 2.75666

In [28]:
if(y_pred.all()<2.5):
    y_pred = np.round(y_pred-0.5)
else:
    y_pred = np.round(y_pred+0.5)
y_pred

array([2., 3., 2., 2., 2., 3., 2., 2., 3., 2., 3., 2., 3., 3., 3., 2., 2.,
       3., 1., 2., 2., 2., 1., 1., 2., 2., 3., 3., 2., 1., 3., 2., 3., 2.,
       3., 3., 3., 2., 2., 2., 2., 2., 2., 3., 2., 2., 3., 2., 2., 1., 2.,
       3., 3., 3., 2., 3., 1., 3., 2., 2., 3., 3., 3., 3., 2., 3., 3., 2.,
       3., 3., 2., 3., 7., 3., 2., 2., 2., 3., 3., 2., 2., 2., 2., 3., 3.,
       1., 1., 3., 2., 4., 3., 3., 3., 2., 3., 1., 3., 3., 3., 3., 3., 3.,
       2., 3., 2., 1., 2., 3., 3., 2., 2., 2., 3., 3., 3., 2., 2., 3., 3.,
       3., 2., 3., 2., 3., 1., 2., 2., 2., 3., 3., 3., 2., 3., 3., 2., 4.,
       3., 2., 3., 3., 3., 2., 1., 2., 2., 3., 2., 4., 2., 1., 2., 2., 2.,
       2., 2., 1., 2., 2., 2., 3., 1., 2., 1., 2., 2., 2., 3., 1., 2., 3.,
       1., 3., 4., 3., 3., 2., 3., 1., 4., 3., 2., 1., 3., 3., 2., 3., 2.,
       3., 4., 2., 3., 2., 1., 3., 3., 2., 3., 3., 2., 2., 3., 2., 1., 2.,
       1., 3., 1., 2., 2., 3., 2., 2., 2., 2., 1., 3., 2., 3., 2., 3., 3.,
       2., 4., 2., 4., 3.

In [29]:
df= (y_pred-y_test)/y_test
df= round(df.mean()*100,2)
print("Error = ",df,"%")

Error =  2.75 %


In [30]:
a = 100-df
print("Accuracy= ",a,"%")


Accuracy=  97.25 %


In [31]:
#SVM
from sklearn.svm import SVR
regressor= SVR(kernel='rbf')
regressor.fit(x_train,y_train)
y_pred = regressor.predict(x_test)
# y_pred

In [32]:
if(y_pred.all()<2.5):
    y_pred = np.round(y_pred-0.5)
else:
    y_pred = np.round(y_pred+0.5)
print(y_pred)

[2. 2. 2. 2. 2. 3. 1. 2. 3. 2. 2. 2. 2. 2. 2. 3. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 3. 2. 2. 1. 3. 2. 2. 2. 2. 3. 2. 2. 2. 3. 2. 1. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 3. 3. 3. 2. 3. 2. 2. 2. 2. 2. 3. 3. 2. 2. 2. 2. 3. 3. 3. 2. 3.
 3. 3. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 3. 2. 3. 3. 2. 1. 3. 2.
 3. 3. 3. 3. 3. 2. 3. 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 2. 2. 3. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 2. 2. 3. 3. 2. 2. 3. 2. 2. 3. 2. 2. 2. 2.
 2. 3. 2. 3. 2. 1. 2. 2. 3. 2. 2. 2. 2. 3. 2. 3. 2. 3. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 4. 2. 2. 2. 2. 2. 4. 3. 3. 2. 3. 2. 2. 3. 2. 2. 4. 2. 3. 3.
 2. 2. 2. 3. 2. 3. 2. 2. 2. 2. 1. 2. 2. 2. 2. 2. 2. 2. 1. 2. 2. 3. 2. 2.
 2. 3. 2. 3. 2. 2. 2. 2. 2. 2. 2. 3. 2. 2. 2. 3. 1. 2. 2. 3. 2. 2. 2. 2.]


In [33]:
df= (y_pred-y_test)/y_test
df= round(df.mean()*100,2)
print("Error = ",df,"%")

Error =  0.15 %


In [34]:
a = 100-df
print("Accuracy= ",a,"%")

Accuracy=  99.85 %
